### ISSUE TITLE
Need to extend Number of Seats in session model

### ISSUE THREAD

**Issue by nurlanf** [Yigitmm/odoo_mod_dev#1]
![image](https://user-images.githubusercontent.com/18286626/96377090-5470d200-1183-11eb-9ec7-73f662855a6d.png)

Hi,

We need additional menu `Class room types` under `OpenAcademy/Configuration` to configure our class room types, which we will define there its `adress` and `seats`.
`Class room types` menu should be only tree view, and editable(top) in tree.
New "Class room type"  Many2one field is needed in Session model.
Current `seats` field in Session should be changed as related field of "Class room type" record.
"Class room type" should be mandatory in Session model.

Good luck
Nurlan

**Comment by nurlanf** [comment]
![image](https://user-images.githubusercontent.com/18286626/96638945-3a6cf600-1321-11eb-9f9e-2a39cc2ae666.png)

**Comment by Yigitmm** [comment]
@nurlanf module updated, please check

**Comment by nurlanf** [comment]
@Yigitmm checked, works, thanks!
