### ISSUE TITLE
Need list of sessions in room type form view

### ISSUE THREAD

**Issue by nurlanf** [Yigitmm/odoo_mod_dev#2]
Create from view for Room type model.
Remove `editable="top"` from Room type tree view
Add one2many field in room type form view in sessions.

**Comment by Yigitmm** [comment]
@nurlanf  module updated, please check

**Comment by nurlanf** [comment]
We don't need additional tabs here, just field in form view. 
![image](https://user-images.githubusercontent.com/18286626/97108575-c9399400-16ce-11eb-8877-4466a5e56d20.png)
 For example like `attendee_ids` field in Session form view

**Comment by Yigitmm** [comment]
@nurlanf module updated, please check
